backend:
  name: github
  repo: dhishooooom-source/remix-of-baingan-magic
  branch: main
  site_domain: statuesque-kataifi-72b37a.netlify.app # e.g. baingan-magic.netlify.app

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "ullu"
    label: "Ullu Pravachan"
    folder: "content/ullu"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "text" }
      - { name: "author", label: "Author", widget: "string" }
